KarateJanNine/Controllers/PhotoGalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KarateJanNine.ViewModels;
using BL_Karate;
using _2.RepositoryLayer;
using BL_Karate.DomainEntityMapper;
using _1.DL_Context;

namespace KarateJanNine.Controllers
{
    public class PhotoGalleryController : Controller
    {
        //
        // GET: /PhotoGallery/ 
        public ActionResult Index()
        {
            KarateDBContext context = new KarateDBContext();
            KarateRepository karateRepository = new KarateRepository(context);
            MapDomainEntity mapDomainEntity = new MapDomainEntity();
            BusinessLayer businessLayer = new BusinessLayer(karateRepository, mapDomainEntity);
            PhotoDetailsVM PhotoDetailsVM = new PhotoDetailsVM(businessLayer);
            var details = PhotoDetailsVM.GetPhotoDetailsVM();
            return View();
        }

        //
        // GET: /PhotoGallery/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /PhotoGallery/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /PhotoGallery/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /PhotoGallery/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /PhotoGallery/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /PhotoGallery/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /PhotoGallery/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public PartialViewResult GetAddPhotoGalleryView()
        {
            return PartialView("_addPhotoGallery");
        }
    }
}

KarateJanNine/Views/Shared/_Layout.cshtml
<link href="~/Content/Layout.css" rel="stylesheet" />

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shorinryu - Tamilnadu</title>


    <!-- Fonts -->


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

@*<body style="background-image: url(Images/bg.jpg)">*@
<body>
    <div class="brand">OKINAWAN &nbsp&nbsp SHORIN-RYU</div>
    <div class="address-bar">Hosur | Tamilnadu | Sensai G Senthil </div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container" >
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>

                        @Html.ActionLink("Home"    // <-- UI Display Caption
                                         ,"Index"  // <-- ActionMethod
                                         ,"Home"   // <-- Controller Name.
                                         ,null     // <-- Route arguments.
                                         ,new { @style = "color:blue" } // <-- Attributes
                                         )


                    </li>
                    <li>
                        <!--<a href="about.html">About</a>-->
                        @Html.ActionLink("Master", null, null, null, new { @style = "color:blue" })

                    </li>
                    <li>
                        <!--<a href="blog.html">Blog</a>-->
                        @Html.ActionLink("Classes", null, null, null, new { @style = "color:blue" })

                    </li>
                    <li>

                        @Html.ActionLink("Gallery",
                                         "PhotoGallery",  // <-- ActionMethod
                                         "Home",   // <-- Controller Name.
                                         null, // <-- Route arguments.
                                         new { @style = "color:blue" } // <-- Attributes
                                         )

                    </li>
                    <li>
                        <!--<a href="contact.html">Contact</a>-->
                      

                        @Html.ActionLink("Contact"    // <-- UI Display Caption
                                         ,"Index"  // <-- ActionMethod
                                         ,"Home"   // <-- Controller Name.
                                         ,null     // <-- Route arguments.
                                         ,new { @style = "color:blue" } // <-- Attributes
                                         )

                    </li>
                    <li style="display: none">
                        @Html.ActionLink("Settings", "Settings", "Home", null, new { @style = "color:blue" })
                    </li>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    @RenderBody()
    <!-- /.container -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Key 2017</p>
                </div>
            </div>
        </div>
    </footer>

    @*  <!-- jQuery -->
    <script src="Scripe/jquery-1.9.1.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="Scripe/bootstrap.min.js"></script>*@

    <!-- Script to Activate the Carousel -->



</body>

</html>

KarateJanNine/Views/Shared/_PhotoGallery.cshtml
@{
    Layout = null;
}

@for (var i = 1; i < 4; i++)
{
    <div class="row">
        @for (var j = 1; j < 4; j++)
        {
            <div class="col-md-4 portfolio-item">
                @{

            var imagePath = "/Images/PhotoGallery/image_" + i + "_" + j + ".jpg";
                }
                <a class="example-image-link" href=@imagePath data-lightbox="example-set" data-title="Click the right half of the image to move forward.">
                    <img src=@imagePath />
                </a>
                @if (i == 1 && j == 1)
                {
                    <h4>
                        <span style="color: green">Martial arts </span>
                    </h4>
                    <p>Okinawan martial arts refers to the martial arts, such as karate, tegumi and Okinawan kobudō.</p>
                }
                else if (i == 1 && j == 2)
                {
               
                    <h4>
                        <span style="color: green">Enter the dragon </span>
                    </h4>
                    <p>Enter the Dragon is a 1973 Hong Kong-American martial arts film directed by Robert Clouse, starring Bruce Lee.</p>
                }
                else if (i == 1 && j == 3)
                {
                    <h4>
                        <span style="color: green">Bruce Lee</span>
                    </h4>
                    <p>Lee Jun-fan, known professionally as Bruce Lee. he founder of the martial art Jeet Kune Do ; Web Sites:  Bruce Lee Foundation</p>
                }
                else if (i == 2 && j == 1)
                {
                   
                    <h4>
                        <span style="color: green">Chinese martial arts</span>
                    </h4>
                    <p>Kung fu and wushu are loanwords from Cantonese and Mandarin respectively that,are used to refer to Chinese martial arts.</p>
                }
                else if (i == 2 && j == 2)
                {
                    <h4>
                        <span style="color: green">Kung fu bear</span>
                    </h4>
                    <p>In general, stronger, larger fighters tend to make use of the bear form, which utilizes the turning of the waist. </p>
                }
                else if (i == 2 && j == 3)
                {
                   
                    <h4>
                        <span style="color: green">The karate kid</span>
                    </h4>
                    <p>The Karate Kid is a 2010 Chinese-American action drama film directed by Harald Zwart. </p>
                }

                else if (i == 3 && j == 1)
                {
                   
                    <h4>
                        <span style="color: green">Martial art uniforms</span>
                    </h4>
                    <p>Martial arts uniforms are produced to the highest standards to ensure that you can feel comfortable and move easily.</p>
                }
                else if (i == 3 && j == 2)
                {
                   
                    <h4>
                        <span style="color: green">Tetsuhiko Asai</span>
                    </h4>
                    <p>Tetsuhiko Asai (浅井 哲彦 Asai Tetsuhiko?, June 7, 1935 – August 15, 2006) was a prominent Japanese master of Shotokan karate. </p>
                }
                else if (i == 3 && j == 3)
                {
                    
                    
                     <h4>
                        <span style="color: green">Bruce Lee</span>
                    </h4>
                    <p>Lee Jun-fan, known professionally as Bruce Lee. he founder of the martial art Jeet Kune Do ; Web Sites:  Bruce Lee Foundation</p>
                }
                else
                {
                    <h3>
                        <a href="#">Project Name</a>
                    </h3>
                    <p>Lee Jun-fan (Chinese: 李振藩; November 27, 1940 – July 20, 1973), known professionally as Bruce Lee, was a Hong Kong .</p>
                }


            </div>
        }
    </div>
}